### ISSUE TITLE
Errors thrown when trying to access any videos, bookmarks, or browse options (IE: popular, newest,ext..)

### ISSUE THREAD

**Issue by livebymisadventure** [dat1guy/UnofficialKissanime#4]

**Comment by dat1guy** [comment]
Can I get a debug log please?

**Comment by livebymisadventure** [comment]
No problem. With the new update it throws an error as soon as I start the addon and crashes.

Here's the Log for that: (http://pastebin.com/daNnCPXT)

**Comment by livebymisadventure** [comment]
After taking that log. I went into the ukap settings and logged out of kissanime profile bookmarks which allowed the addon to start-up but threw an error on the first thing I tried to access, which was "popular".

Here's the log for that: (http://pastebin.com/49L6Ztir)

Thanks man.

**Comment by dat1guy** [comment]
@livebymisadventure For that first error, it's weird that you'd get a syntax error on that line.  That's valid Python.  What version of Kodi are you running?

Anyway, I believe the problem is solved with version 1.2.0, because I got rid of that line anyway in favor of simpler logic.  I think as of right now the add-on is at 1.2.2, so that problem should be fixed.  Let me know if it's not fixed.

For your 2nd problem, I have no idea what to do.  I use a parser called BeautifulSoup to parse the HTML of the website, and BeautifulSoup is failing on something that it usually has no problem with.  Furthermore, although other people have hit it, I never have :( I guess if you could do the following, I might be able to put in a filter for that particular string:
 - In the UKAP settings, under the Debug category, enable to dump html on load failure.
 - Send me the debug log as well as the dump of the HTML it tripped on.
 - You may need to use Google Drive to host the HTML if paste bin can't handle it.

**Comment by livebymisadventure** [comment]
I'm running 16.1.
I'll get back to you asap and let you know if 1.2.2 fixed my problems.
If that didn't fix it, I'll see if I can do those 3 things you suggested.

**Comment by livebymisadventure** [comment]
Unfortunately that didn't resolve the issue. But I can now start the addon and also sign into and view my bookmarks list. But if I try accessing anything further it gives an error.

Here's the log of me trying to access "popular": (http://pastebin.com/ypELjhGH)
And I have enabled "dump html", but I don't know where to find the dump to send it to you.

**Comment by livebymisadventure** [comment]
Also, In my addons folder I have 2 "beautifulsoup" scripts.
One called "script.module.beautifulsoup" and a separate on called "script.module.beautifulsoup4".
Is this odd? Do you think it could have anything to do with this?

**Comment by dat1guy** [comment]
I think you need to turn on debug logging.  Go to Settings->System->Logging->Enable debug logging.  Then try again.  The HTML dump should be right above the exception stack trace.  You'll know if debug logging is turned on because you'll see a bunch of other messages that start with "DEBUG: The Unofficial KissAnime Plugin:".

**Comment by livebymisadventure** [comment]
Oh, I understand now. Thanks. 
Ok I believe I have it. This is me booting the addon, then selecting popular to get the error. 
The log: (http://pastebin.com/cYvYJ36F)

**Comment by dat1guy** [comment]
Yeah, BeautifulSoup has no problems with that HTML on my system, although I'm using Kodi v17, and I don't know if that makes a difference or not.

Regardless, I just pushed out version 1.2.2.1 to the repository a minute ago.  Please let me know if that version resolves the issue.

**Comment by livebymisadventure** [comment]
You sir, have gone above and beyond. It's much appreciated. The problem is resolved with the new update. Thanks.

However, I have noticed one more small problem arise which I will post a new issue for so that you can close this one.
